version: "2"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx
    links:
      - app
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - conf:/nginx
    environment:
      - SECRET=<express-session secret>
      - DB_USER=<mongoDB username>
      - DB_PS=<mongoDB password>
    ports:
      - "<Host PORT>:<Container PORT>"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<mongoDB username>
      - MONGO_INITDB_ROOT_PASSWORD=<mongoDB password>
    volumes:
      - ./data:/data/db
volumes:
  conf:
